### ISSUE TITLE
Create a 'no results' result for boston.gov/news or /events

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#10]
Currently nothing shows up when you search and get nothing:

https://www.boston.gov/news?title=Lorem+ipsum&field_published_date_value%5Bmin%5D%5Bdate%5D=&field_published_date_value%5Bmax%5D%5Bdate%5D=

@jduffy2001 what should the copy be if you get nothing? "No Results"?

**Comment by matthewcrist** [comment]
@sebastianebarb can you put together what you'd want from a generic no results view on the listing pages?

**Comment by sebastianebarb** [comment]
https://drive.google.com/file/d/0B0RwQU94BhGeX2NzUWdKZGFDZEk/view?usp=sharing
![event not found](https://cloud.githubusercontent.com/assets/20642299/20499072/d3ecd966-affd-11e6-81da-37862999d39e.png)

**Comment by reillyzlab** [comment]
@sebastianebarb can you also look at the 'no results' within pages that have in page search

Few examples:

https://www.boston.gov/pay-and-apply

https://www.boston.gov/guides

**Comment by sebastianebarb** [comment]
Updated info for this and on the design board. https://waffle.io/CityOfBoston/design-team-workflow/cards/58d3eb3b1757a1f7033ea078
All "not found" messages should be accompanied by a new search field, text, and popular hits for the category.

![pay and apply not found](https://cloud.githubusercontent.com/assets/20642299/26248934/359b1d7a-3c72-11e7-97d9-6337bcb638c5.png)
![guides not found](https://cloud.githubusercontent.com/assets/20642299/26248933/359a8cb6-3c72-11e7-9485-6e3c2d42354f.png)

**Comment by jimafisk** [comment]
The missing exposed filters and no results behavior for views referenced in components are fixed per:
- https://www.drupal.org/node/477244#comment-12169011
- https://www.drupal.org/node/903034#comment-12169006

@sebastianebarb - I assume the "Search" is a filter local to the table, not a site-wide search? Also, just a usability question, should we accommodate a simple way to clear out the previous query (similar to the reset button in the default filters)?

Implementing the design specs has a few technical challenges due to the structure of these pages. I'm currently looking into how to get around these, but just for reference this is generally how these pages are structured:

![news_regions](https://user-images.githubusercontent.com/5913244/28228266-c362196e-68ab-11e7-812e-137ddd731570.png) 

We can add a "Global: View area" in the no results behavior of the View, which should allow us to create displays like the grid of guides and forms above. Is there specific criteria we should use to decide which guides / forms are returned (e.g. the most recent published, or ordered alphabetically by title)?

**Comment by jimafisk** [comment]
@sebastianebarb I spoke with @matthewcrist this morning. Ideally we will redirect no results to search.boston.gov with the search text and appropriate filters applied, example: https://search.boston.gov/?utf8=%E2%9C%93&query=test&facet%5B%5D=post

If we want to do grids for guides and forms, we will need to treat "no results" slightly differently.

**Comment by matthewcrist** [comment]
Ready on staging.
