### ISSUE TITLE
Linkit upload document option not working

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#1021]
Users, especially content authors, can use the linkit button in our WYSIWYG field to upload documents onto their pages. Here's what that looks like, a user clicks "open file browser":
![image](https://user-images.githubusercontent.com/7929556/37056252-d75d2486-2151-11e8-91ed-d2bdadf47c97.png)

There's an AJAX error message popping up that's preventing them from completing the upload. It looks like this:
![image](https://user-images.githubusercontent.com/7929556/37056325-184c0c78-2152-11e8-926a-41740cc6c7a9.png)

@jimafisk I assume this bug might have to do with your work on S3, but wanted to flag for you.

**Comment by jimafisk** [comment]
Error message for reference:
```
An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /imce?jsop=upload&dir=.
StatusText: n/a
ResponseText: {"data":{"added":[{"name":"test_2.png","size":19352,"width":783,"height":359,"date":1520373542,"fsize":"18.9 KB","fdate":"03\/06\/2018 - 4:59pm","id":"78985"}],"dirsize":"75.59 KB"},"messages":{"status":["The file has been renamed to \u003Cem class=\u0022placeholder\u0022\u003Etest_2.png\u003C\/em\u003E.","\u003Cem class=\u0022placeholder\u0022\u003Etest_2.png\u003C\/em\u003E has been uploaded."]}}
ReadyState: ,
```

**Comment by jimafisk** [comment]
Additional error info:
```
Uncaught TypeError: jQuery(...).data(...) is not a function
    at HTMLIFrameElement.onload (https://0.0.0.0/imce?app=Linkit|sendto@Drupal.linkit.IMCECallback&absolute=1:1:42)
    at HTMLBodyElement.<anonymous> (https://0.0.0.0/misc/jquery.js?v=1.4.4:114:484)
    at $.fn.init.domManip (https://0.0.0.0/misc/jquery.js?v=1.4.4:120:406)
    at $.fn.init.append (https://0.0.0.0/misc/jquery.js?v=1.4.4:114:424)
    at $.fn.init.c.fn.(anonymous function) [as appendTo] (https://0.0.0.0/misc/jquery.js?v=1.4.4:122:247)
    at x (https://0.0.0.0/sites/all/modules/contrib/imce/js/jquery.form.js?k=p58f5h:7:3572)
```

**Comment by jimafisk** [comment]
This issue appears to have been introduced in the Drupal core upgrade from version `7.56` to `7.57`. We can't roll back, because this was a critical security update (https://www.drupal.org/SA-CORE-2018-001). The issue was likely related to the fix titled "jQuery vulnerability with untrusted domains - Moderately Critical - Drupal 7 - CVE-2017-6929" detailed in the link above.

To test, I rolled back the core version to `7.56` in `make.yml` like so:
```
api: 2             
core: 7.56         
                   
defaults:
  projects:
    subdir: contrib

projects:
  drupal:
    version: 7.56
    #type: core
    patch:
```
And re-ran the build `./task.sh build:local` (note you can't simply `drush dl drupal-7.56` because you will receive this error: "It's forbidden to download drupal core into an existing core.")

This clears up the AJAX error and the LinkIt > IMCE functionality returns to normal.

**Comment by jimafisk** [comment]
Upgrading IMCE to the newest stable version should fix this issue: https://www.drupal.org/project/imce/issues/2951577

I also removed the patches that were previously being applied that are now included in the contrib codebase:
- https://www.drupal.org/files/issues/imce.extension.validator-1018344-3.patch
- https://www.drupal.org/files/issues/imce-n2357871-12.patch
  - Seems to be committed per https://www.drupal.org/node/2357871#comment-12096563 although I don't see 1-to-1 representation in current module code

**Comment by jimafisk** [comment]
@jduffy2001 this should be on prod now, please re-open if it's not fixed. Thanks!
