### ISSUE TITLE
Testing for new upload connection to AWS S3 on Boston.gov/Hub

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov#1049]
#### Expected Behavior/Acceptance Criteria 
<br>
We want to make sure the experience of uploaded documents, images, and other files to Boston.gov and the Hub mirrors something similar to the experience we have now.
<br><br>
Currently, there are three different ways to upload documents to both sites:

1. LinkIt option is a WYSIWYG field
2. Media Browser option in a WYSIWYG field
3. Through components on different content types

#### Actual Behavior
<br>
Concerns with uploading using AWS include:

1. Slow performance (longer than 5 seconds)
2. Upload not working at all
3. Links not being made
4. Images not rendering on display
5. Error messages appearing when uploading or removing images

#### Browser
<br> 
All browsers (prioritize Chrome, Firefox, Internet Explorer)

#### Device
<br> 
All devices

#### Example URL
<br> 

- [Page with uploads through LinkIt and Media Browser options](https://www.boston.gov/departments/elections/results)
- [Pages with component uploads](https://www.boston.gov/departments/environment/climate-ready-boston#report)

#### Relevant Screenshot(s) or Logs
<br> 
Different options for uploading documents:

Linkit (in WYSIWYG field):
![image](https://user-images.githubusercontent.com/7929556/39630325-04a7c1e0-4f7d-11e8-8de3-c9b1cbe8f01b.png)

Media Browser (in WYSIWYG field):
![image](https://user-images.githubusercontent.com/7929556/39630391-2e3e230a-4f7d-11e8-8773-067be2d241fa.png)

Component uploads (example, mini grid):
![image](https://user-images.githubusercontent.com/7929556/39630405-38cff442-4f7d-11e8-813b-93277e225d48.png)

#### Steps to Reproduce the Behavior/How to Test
<br> 

Options for uploading documents in Drupal:
<br>
**_Linkit option:_**

- In a WYSIWYG field, highlight the text you want to hyperlink and click the “link to content” button (chain with + sign on it).
- New window opens up. Click on the “open file browser” button. 
- New window opens up. Content authors need to click on folder for the current month for the current year. After clicking the folder, and upload option appears in the top right.
- Permissions are different for site admins (we should test out permissions options). Site admins are forced to load all documents uploaded to Drupal before being allowed to upload a new document. This adds a significant amount of time.
- Click on the “upload” button in the top left, choose a file from your desktop, and click “upload.” When the document finishes uploading, it will appear as a blue link in the right side of the window.
- Click the “insert file” button in the top of the window. The window will close, returning you to your original LinkIt window that now features a relative link.
- In the LinkIt window, click “insert link” in the bottom left to add the link to the page.

**_Media Browser option:_**

- In a WYSIWYG field, highlight the text you want to hyperlink and click the “media browser” button (looks like a landscape photo at the right).
- Choose a file off your desktop and click “next.”
- At the next window, you need to choose a destination. To test Amazon, check “Amazon Simple Storage Service.” To upload to where we have in the past, select “public local files served by the webserver.” Click “next.”
- In the next window, you need to give your file a name you will remember. After adding the name, click “save” at the bottom of the window.
- After clicking “save,” you’re taken to window where you’re given different options for displaying the document. None of them work great. So, you can just copy the “edit” link at the top of the page and close the window.
- Highlight, again, over the text that you want to link to the document. This time, you need to click the “link” button in the WYSIWYG field (looks like a chain, next to “link to content” button). 
- In the window that pops up, past the url of the document into the url field. Make sure to remove the “https://edit.boston.gov” part of the url to make it a relative link. You can also just change “edit” to “www” to make the link work.
- After pasting in and setting up the url, click “OK” in the window. The link is now added to the page.

**_Component option (add a mini grid):_**

- First, click on the components section in the left side of the page.
- In the “component type” dropdown, select “Group of Links - Mini Grid” and click “add another component.”
- The page will refresh and you’ll see an empty component. Click on “links” to open up your options for adding links.
- In the paragraph type, choose “document” and click “add new paragraph.”
- In the new empty link section, click “browser” and upload a document from your desktop.
- Choose a file off your desktop and click “next.”
- In the next window, you need to give your file a name you will remember. After adding the name, click “save” at the bottom of the window.
- After clicking “save,” the document is added to the component. By default, whatever the title of the document is will be what a user sees on the page. You can also add your own title in the “title” field.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by jduffy2001** [comment]
@jimafisk let me know if you need further clarification.

**Comment by BrutiAnteneh** [comment]
S3 migration appears to be affecting file uploads on content types. When I click "Attach" the page reloads instead of opening up a dialogue box to add the file. Will test again once the S3 migration is finished running. See examples below.

**Guide Page - adding Intro image**

Clicking Attach reloads, and brings user to the top of the page 

![guide page](https://user-images.githubusercontent.com/33470951/41563453-98a0bc62-731d-11e8-9847-41a109741c06.png)



**Article page**

![article pages](https://user-images.githubusercontent.com/33470951/41564748-d977d780-7321-11e8-91a2-5dd04fad7e1a.png)

**Comment by jimafisk** [comment]
@BrutiAnteneh thanks for identifying the issue above and logging this bug report. The reason this was happening is because jQuery couldn't properly load:

![jquery](https://user-images.githubusercontent.com/5913244/41566676-8604aade-732a-11e8-8b64-53c0ae09b8a2.png)

When we enable S3 we need to also disable the "Aggregate JavaScript files" settings under the Development > Performance tab (`/admin/config/development/performance`)

**Comment by jduffy2001** [comment]
Link It module is working for the "content author" permission level. There doesn't appear to be a noticeable delay when uploading a document.

But, when a user clicks "insert link" after uploading a document, they're getting relative url instead of a full url. Since our documents have S3 domains at the start, the links are appearing broken on the page:
![image](https://user-images.githubusercontent.com/7929556/41993319-10ee50c4-7a19-11e8-909e-256ce46e117f.png)

It should be something like this:
https://s3.amazonaws.com/media.boston.gov/s3fs-public/document-file-06-2018/school_zone_flasher_assembly-_detail_1_3.pdf

But instead I'm getting this:
https://edit-stg.boston.gov/sites/default/files/imce-uploads/2018-06/school_zone_flasher_assembly-_detail_1_1.pdf

Uploading documents through components is working fine. But, it is giving me a "s3.amazonaws.com" url like the one mentioned above. We should create a custom url for these.

Fin suggested static.boston.gov

**Comment by jduffy2001** [comment]
One note, all of our images appear broken now in the media library:
![image](https://user-images.githubusercontent.com/7929556/41993720-442a9be0-7a1a-11e8-9d82-cd2bbb9350d3.png)

**Comment by reillyzlab** [comment]
Brought in issues so increase db size instead. Closing
