### ISSUE TITLE
Set up a sample database for Boston.gov

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#137]
We obviously can't have our production database available for folks to use. But it would be great for people to have a sample database to use to populate content in their development environment when developing against Boston.gov. 

How?
Create fixtures - representations of the database in the code that can get applied programmatically when people set up their development environment.

**Comment by gilronc** [comment]
I can probably help out with the mundane tasks......give me a start and i can probably finish it.  I believe a sample DB is needed for anyone that wants to test out or contribute to different features.

**Comment by hackajesse** [comment]
@gilronc that's great to hear! What type of help do you need to start?

**Comment by gilronc** [comment]
The "easiest" way i can think of getting a quick demo platform out to the public is to create a clone from your production installation and delete all nodes/content.  Essentially, you would be providing me with a skeleton of the site and i can create Demo/Example content for all content types and paragraphs components.  Other developers would be able to use that package to get a quick idea of how everything works/is structured and can start prototyping components or various features based on that snapshot.  

That's the easiest way i can see this being done at the moment to get developers to start testing the code.

 An ideal solution would be to use Devel Generate.  A developer would be able to download a blank copy of the website and generate content as needed.  Devel Generate is not fully compatible with Paragraphs at the moment so that option might have to be implemented at a later date.

In terms of Database fixtures, i don't have a clue how to set that up or to get it started, if there's anyone that can mentor me, i'm a willing and capable learner.

**Comment by cob-hondo** [comment]
Thanks to @finneganh, we now have a basic Docker install that will get you up and running pretty quickly with a fresh DB.
