### ISSUE TITLE
You can see the apache page at this url

### ISSUE THREAD

**Issue by HellooooNewman** [CityOfBoston/boston.gov#227]
http://mayors24.boston.gov/
Should probably have a redirect in place.

**Comment by sugaroverflow** [comment]
+ You can get to http://mayors24.boston.gov/ if you poke around 311 requests that are coming from Lagan, but https://mayors24.cityofboston.gov/ directs to 311.boston.gov (the URL doesn't change)

**Comment by hackajesse** [comment]
@sugaroverflow this predates me. Should those two pages redirect to http://www.cityofboston.gov/311 ?

**Comment by sugaroverflow** [comment]
@hackajesse I would think so! That or 311.boston.gov ? Not sure where the redirect would be handled though since it's on the boston.gov domain. 

When we launched 311, I'm pretty sure we redirected any mayors24.cityofboston.gov to boston.gov/311 or 311.boston.gov (depending on the request, some of them go to the new portal).

**Comment by matthewcrist** [comment]
Closing this one. We'll be switching on a new 311 in the near future, and this is going away.
