### ISSUE TITLE
Create Keyboard Shortcuts for Hub

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#262]
**Goals:**

- As a user, I would like to be able to quickly navigate to specific pages on the website.
- As a user helping other employees, I would like to be able to quickly provide them with the navigation pattern to get to specific pages on the website.
- As a site administrator, I would like to be able to add keyboard shortcuts to the Hub that could be used to populate a list view.

**Acceptance criteria:**

- When on the Hub, if a keyboard shortcut is used by a user, then the user is taken directly to a URL/page (i.e. the shortcut calls the URL). Example pages include:  
  1. h + t = takes users to /tools  

  2. h + d = takes users to /employee-directory
  3. h + l = takes users to /details-and-forms
  4. h + f = takes users to homepage
  5. h + q = takes users to /need-something-else
  6. ? = takes users to article about short cuts

- A site administrator can easily add a keyboard shortcut to the website whenever need be without needing additional development work.
- A site administrator can easily populate a page with a 'list' of keyboard shortcuts.
- Incorporate Google Analytics tag, so that every time someone using one of the above shortcuts analytics registers the shortcut as an 'event'.  

**Success metrics: **

- 35% of traffic to the above mentioned pages become accessed via the above keyboard shortcuts.
- Qualitatively feedback from employees is that these shortcuts have helped them use the site better and that they have helped employees share how to navigate to certain Hub pages more easily.

**Comment by matthewcrist** [comment]
? should take users to keyboard shortcut article

**Comment by matthewcrist** [comment]
We should use this library: https://github.com/madrobby/keymaster

@reillyzlab you'll need to come up with a detailed list of shortcuts prior to us starting this.

**Comment by matthewcrist** [comment]
Here's how we're going to implement this. We will use this module https://www.drupal.org/project/keyboard_shortcut. That module will get us keyboard shortcuts that are editable by an admin. It allows us to link to pages or use JS functions. Once installed, we need:

 * Ability to define roles on keyboard shortcuts
 * Ability for anonymous, logged out users to use shortcuts (the module only uses logged in users currently)
 * Should not load JS if user if there are no shortcuts for the user's role

This will allow us to enable this module for Boston.gov and The Hub, though Boston.gov may never use it.

## Testing steps

 * Admin creates shortcut that is admin only
   * Admin should be able to use shortcut
   * Anonymous user should not be able to use shortcut
   * Anonymous user's browser should not download js
 * Admin creates shortcut that is accessible to anonymous users
  * Admin can use shortcut
  * Anonymous user can use shortcut

**Comment by jimafisk** [comment]
@matthewcrist I rolled a patch that should take care of the first 2 bullets (define roles per binding & allow anonymous users to execute shortcuts): https://www.drupal.org/node/2839535

I'll start looking into dynamically loading js. I think we'll need to do an access check in keyboard_shortcut_init() of keyboard_shortcut.module.

I've performed the testing steps above and everything looks good aside from the browser downloading js. Anyone else want to test to double check? Thanks!

**Comment by jimafisk** [comment]
New patch dynamically loads js: https://www.drupal.org/node/2839535#comment-11843362 If no shortcuts exist for user's role, browser does not load library.

Ran through Matt's testing scenarios and it checks out on my end. Much appreciated if someone else could confirm. Thank you!

**Comment by reillyzlab** [comment]
Re-opening to make sure I remember to test in QA.

**Comment by reillyzlab** [comment]
@matthewcrist @jimafisk not working for 'anonymous' users (i.e. when not authenticated).

**Comment by reillyzlab** [comment]
@matthewcrist @jimafisk still only working if the user has the 'administrator' role.

**Comment by matthewcrist** [comment]
@jimafisk can you take a look at this when you're back in?

**Comment by jimafisk** [comment]
It looks like the hub_keyboard_shortcuts feature did not enable with hook_update_7014:
![hook_update_code](https://cloud.githubusercontent.com/assets/5913244/22514171/6fd9a6dc-e86c-11e6-8c24-d997228d040b.png)
![feature_not_enabled](https://cloud.githubusercontent.com/assets/5913244/22514072/2011de6c-e86c-11e6-8eb8-09d0c1f0e6e0.png)

Without that, the global permissions are still preventing anonymous users:
![permissions_missing](https://cloud.githubusercontent.com/assets/5913244/22514107/38288424-e86c-11e6-9ebe-586edefe953a.png)

**Comment by matthewcrist** [comment]
This should be set now.

**Comment by reillyzlab** [comment]
@matthewcrist still only working for site administrators

**Comment by matthewcrist** [comment]
This is working on prod now.

**Comment by jimafisk** [comment]
@reillyzlab are these still not working for anonymous users?

@matthewcrist I haven't looked at this in a while, but the issue was the global permissions need to be set so anonymous users can use shortcuts. Once that is allowed, the per binding permissions should be obeyed. I had created a feature to enable the global permission, but for some reason in never seemed to enable in the db. My theory is a prior hook_update_N() was failing, but I never confirmed that.

**Comment by matthewcrist** [comment]
It’s working on prod for authenticated users, which is what everyone is there. We have a different way of setting permissions on the users, so I think your module was getting reset. Look at:

docroot/sites/hub/settings/permissions.settings.php

On Fri, Apr 07, 2017 at 9:06 AM Jim Fisk

<
mailto:Jim Fisk <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/reillyzlab
are these still not working for anonymous users?

https://github.com/matthewcrist
I haven't looked at this in a while, but the issue was the global permissions need to be set so anonymous users can use shortcuts. Once that is allowed, the per binding permissions should be obeyed. I had created a feature to enable the global permission, but for some reason in never seemed to enable in the db. My theory is a prior hook_update_N() was failing, but I never confirmed that.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/CityOfBoston/boston.gov/issues/262#issuecomment-292531230
, or

**Comment by jimafisk** [comment]
Got it, makes sense. Shortcuts weren't ever deployed to boston, just the hub which has no anonymous users. I've added this to bos: https://github.com/CityOfBoston/boston.gov/pull/590

It also looks like the contrib module name in hub_profile_update_7014() is incorrect. It should be keyboard_shortcut not keyboard_shortcut**s**. Does anyone remember if we had to enable this manually?
