### ISSUE TITLE
As a content author, I want to be able to add related guides to events

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#299]
## Acceptance Criteria

\* Content author can add related guides to events

\* Allows for more than one guide to be entered

**Comment by hackajesse** [comment]
Checked

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Guides" becomes "Related guides" (note lower case). 
Help text copy change:
"Which guides are relevant for this event?"

**Comment by matthewcrist** [comment]
@asalsman i'm not seeing related guides on events

**Comment by hackajesse** [comment]
Admin side is fine. Events component UI doesn't display events when using the Related Events view.

**Comment by asalsman** [comment]
@hackajesse I'm not following. Can you throw an example?

**Comment by matthewcrist** [comment]
@asalsman related events aren't showing up on events pages or guides. Take a look st the trash and recycling guide

On Tue, Jan 31, 2017 at 5:15 PM Adam Salsman

<
mailto:Adam Salsman <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/hackajesse
I'm not following. Can you throw an example?

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/CityOfBoston/boston.gov/issues/299#issuecomment-276510671
, or

**Comment by hackajesse** [comment]
Used the Related Guides view instead of Related Events (general) and this worked in the UI. Closing.
