### ISSUE TITLE
As a content author, I want to be able to add related neighborhoods to posts.

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#306]
## Acceptance Criteria

\* Content author can add related neighborhoods to posts  
\* Neighborhoods should be listed as checkboxes

\* Checkboxes should be in two-columns (confirm this is possible)

\* Allows for more than one neighborhood to be entered

**Comment by hackajesse** [comment]
Copy for this related content item:
"Related neighborhoods" (note lower case).
Help text copy change:
"Which neighborhoods are relevant for this post?"

Can the checkboxes be listed in two columns, alphabetical order decending, top to bottom, left column to right column?

**Comment by matthewcrist** [comment]
This will need to be one column.

@asalsman we should use @jimafisk's places / neighborhoods filed here.

**Comment by reillyzlab** [comment]
Can't test this one b/c lack of functionality on Hub

**Comment by hackajesse** [comment]
Looks good on Boston.gov. Closing.

**Comment by hackajesse** [comment]
Re-opening. Got something to check again.

**Comment by hackajesse** [comment]
On Posts, the neighborhood checkboxes appear in addition to the neighborhood auto-fill field. Check node 11561 @jimafisk @asalsman. 

However, this is not a blocking issue. I will prob open a new ticket - @matthewcrist your call after chatting w/ @jimafisk.

**Comment by matthewcrist** [comment]
If the related aspect is working, close this and open a new one for that bug.

On Wed, Feb 01, 2017 at 3:16 PM Jesse Biroscak

<
mailto:Jesse Biroscak <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

On Posts, the neighborhood checkboxes appear in addition to the neighborhood auto-fill field. Check node 11561
https://github.com/jimafisk https://github.com/asalsman
.

However, this is not a blocking issue. I will prob open a new ticket -
https://github.com/matthewcrist
your call after chatting w/
https://github.com/jimafisk
.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/CityOfBoston/boston.gov/issues/306#issuecomment-276769106
, or

**Comment by hackajesse** [comment]
Created separate issue for the bug. Closing. Ref #414
