### ISSUE TITLE
As a content author, I want to be able to add "other related content" to posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#307]
## Acceptance Criteria

\* Content author can add related content that isn't covered in other related content fields to posts

\* Allows for more than one relation to be entered

\* ~~Do not include How To content type~~

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Related Content" becomes "Other related content" (note lower case).
Help text copy change:
"Which articles, how tos, and / or other content are relevant for this post?"

Content types available for this field should only include: Article, How Tos (now included!), Landing Page, and Script Page.

Not required.

**Comment by reillyzlab** [comment]
@matthewcrist 

- Allowed to add internal items but the list shows in with red letters. Non blocking since you can use the feature, but I would imagine it will freak some content authors out.
![img_5840](https://cloud.githubusercontent.com/assets/20731897/22520484/71abe702-e882-11e6-8d48-2e18100d94e6.JPG)

Was only able to add content types as specified, but could not check some of the content types because don't have people profiles, place profiles

**Comment by asalsman** [comment]
@hackajesse: That red *may* be an weird bug with my error handling (was put in place before field data migration plan). I will take a look.

**Comment by matthewcrist** [comment]
Let's track it separately, as it's not a major issue.

**Comment by hackajesse** [comment]
I get the same red copy and outlining. @reillyzlab were you also creating this new issue? Otherwise, this looks good. Closing.
