### ISSUE TITLE
Search Testing

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#321]

**Comment by lflockwood** [comment]
Search algorithm seems off for some things. I typed "cold" and got the following:  
![image](https://cloud.githubusercontent.com/assets/20707572/21273605/5f39e386-c392-11e6-88e5-345c669e15b3.png)

**Comment by lflockwood** [comment]
Some results show the page type and others don't seem to (see screenshot below). Also, is there a way to filter results? Eg by pdfs or page types?

![image](https://cloud.githubusercontent.com/assets/20707572/21274407/0f1517d2-c396-11e6-92d2-fc11c57d00b6.png)

**Comment by reillyzlab** [comment]
1) Search pagination for words 'next' and 'previous' don't have hover state. Should it?

2) Some of the news have a 'news' tag and some do not. When I search for 'digital team' the first press release that appears is on cityofboston.gov and does not include the news tag. I call this out because this was confusing to me why some news did and and some news didn't the tag. If we can't add tag, can we clarify why some do and don't get tags?

3) The tags on the right side appear to be floating towards the top rather than the middle. Assuming we want them to float center vertically.

URL for 2 and 3: 
https://cob-search.herokuapp.com/?utf8=%E2%9C%93&q=%22digital+team%22

Photo for 2 and 3: 
![search image-new boston gov](https://cloud.githubusercontent.com/assets/20731897/21273827/62080c72-c393-11e6-910a-f835a97476f3.PNG)

4) First time I searched 'digital team' I returned these results:
![search image-new boston gov](https://cloud.githubusercontent.com/assets/20731897/21273960/f3094a24-c393-11e6-8909-1104262cff27.PNG)

Second time I returned these results:
![digital team 2](https://cloud.githubusercontent.com/assets/20731897/21273981/06a6a9dc-c394-11e6-8abf-f7d542fca261.PNG)

May be an indexing thing, but wanted to flag just in case.

5) Searching Martin Walsh, Mayor Martin Walsh, and Mayor Martin J. Walsh returns 'Atyia Martin' before results involving Mayor Walsh. May need to bias to bring her results down when related to the Mayor.

https://cob-search.herokuapp.com/?utf8=%E2%9C%93&q=martin+walsh

https://cob-search.herokuapp.com/?utf8=%E2%9C%93&q=Mayor+martin+walsh

https://cob-search.herokuapp.com/?utf8=%E2%9C%93&q=Mayor+martin+J.+walsh

Ex: 
![search martin walsh](https://cloud.githubusercontent.com/assets/20731897/21274072/6830e884-c394-11e6-87d4-4391d4c016ac.PNG)

6) Not all person profiles are turning back the person profile tag. Martin J. Walsh gets tagged with Person_Profile, but Atyia Martin does not.

![person profile](https://cloud.githubusercontent.com/assets/20731897/21274103/876980d0-c394-11e6-8ab8-5c6b9ed7a094.PNG)

7) Person Profile looks like Person_Profile -  note underscore (see image above)

8) Breadcrumb says "search"...not sure if you want to incorporate 'search results' into it. Don't have any opinion just wanted to flag for consideration.
![breadcrumb](https://cloud.githubusercontent.com/assets/20731897/21274143/b793acb8-c394-11e6-84c3-e329c0d94b14.PNG)

9) Searching public notices - /public-notices shows up third. May be fine if at least put above 'Plans, Reports, and notices at: https://www.boston.gov/departments/neighborhood-development/plans-reports-and-notices
![public notices](https://cloud.githubusercontent.com/assets/20731897/21274213/f633248a-c394-11e6-8fc2-2fd9c9ab9f3d.PNG)

10) Searching the words news only turns back results for the old compilation of news on cityofboston.gov
https://cob-search.herokuapp.com/?page=5&q=news

![news](https://cloud.githubusercontent.com/assets/20731897/21274241/280b4762-c395-11e6-8e94-0b2d9e550b00.PNG)

11) If I hit 'enter' to process search results with no words input the following returns:
https://cob-search.herokuapp.com/?utf8=%E2%9C%93&q=

![simply hit enter](https://cloud.githubusercontent.com/assets/20731897/21274304/86411dfc-c395-11e6-8075-880888fec5c6.PNG)

12) Consider synonym pubic = public

**Comment by matthewcrist** [comment]
@lflockwood & @reillyzlab there's a bug where the type isn't showing for some Boston.gov items, but for CityOfBoston.gov items there won't be a type (unless we edit those pages). Is that too confusing?

**Comment by reillyzlab** [comment]
@matthewcrist completely makes sense, but wanted to flag in case we'd consider some point of clarification (statement at end?) so users don't get confused on why some do and some don't but I could just very well be overthinking it

**Comment by matthewcrist** [comment]
@reillyzlab we could have a "type" for cityofboston.gov results, like "archived" or "old"

**Comment by matthewcrist** [comment]
@lflockwood and @reillyzlab i pushed an update with filtering, some fixes to the bugs @reillyzlab saw, and have tweaked the algorithm a little. take a look and let me know if you see anything glaring.

**Comment by matthewcrist** [comment]
there will be a slight delay for all the types to appear in the search as it's awaiting a reindex
