### ISSUE TITLE
Events component should pull in Public Notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#334]
A public notice content type tagged with any related content should show up in the events component on the specified related content node(s).

- [x] Be mobile responsive - just like an event card
- [ ] It's possible for a featured item to be either a public notice or an event
- [x] If a featured item is a public notice, the call to action button should read "Notice details"
    Reference  #117
    
- [x] Public notices and events are integrated and ordered in date descending
    Small cards should order date descending. Meaning a set of events / public notices happening December 8, 13, 20, and 30 should order: Top Left (TL) = 8; TR = 13; BL = 20; BR = 30.
    
- [ ] If a featured item is an event, the call to action button should read "Event details"
- [ ] Public notices should display the noticing department
    Per the comp
    
- [x] See All button in the comp should be flexible
    The "See all" button generates from the events component and is user-defined. Don't modify.
    
- [ ] Featured items should not appear among the smaller cards (ref #117)
- [x] Public notices and events should have the same hover-over states as the existing events component
     (different colors for Hub vs Boston.gov - keep consistent within each brand). 
    
- [x] Public notices should automatically display the appropriate icon
    [https://drive.google.com/open?id=0B0RwQU94BhGeU3BOUVE3UEtibk0](https://drive.google.com/open?id=0B0RwQU94BhGeU3BOUVE3UEtibk0)
    
- [ ] Comp for how this looks in an events component. 
    Note the small card and the featured card show two different instances of a public notice card in the events component.
    
    ![public notices hero](https://cloud.githubusercontent.com/assets/20642299/20630836/76830672-b301-11e6-9517-1cb2783210a5.png)

**Comment by hackajesse** [comment]
@jimafisk @asalsman @matthewcrist can you give this a review and ask any questions you might have?

**Comment by hackajesse** [comment]
This is a dev follow up issue to #205

**Comment by hackajesse** [comment]
This is a duplicate of #315 . Closing.

**Comment by hackajesse** [comment]
Taking the place of #315

**Comment by asalsman** [comment]
I feel like this should be two discrete issues:
1) Allow Public Notices to be returned in with Events in collections
2) User-facing display implications of allowing Public Notices to be included in lists.

The second is obviously dependent upon the first, but still.

In my experience, any ticket that comes in larger than an 8 needs to be broken down into more focused subtasks.

My $0.02.

**Comment by asalsman** [comment]
@hackajesse : Currently, Featured Items on the Upcoming Events component include Events and Posts. Adding Public Notices is trivial, but are Posts supposed to remain?

**Comment by asalsman** [comment]
@hackajesse: The attached icon for public notices doesn't match the style on public/hub with dark background and lighter accents as is seen for events or in the attached comp. I also don't see one anywhere on the file system. Is that discrepancy a feature or bug?

Public: https://www.boston.gov/sites/all/themes/custom/boston_public/src/img/news-default-thumb.svg
Hub: https://www.boston.gov/sites/all/themes/custom/boston_hub/src/img/news-default-thumb.svg

**Comment by hackajesse** [comment]
@asalsman does [this](https://drive.google.com/open?id=0B0RwQU94BhGeU3BOUVE3UEtibk0) work for you? Assuming you'd create a dark background and overlay the icon over it. However, if that's not the case and you need a dark background icon from @sebastianebarb, let us know asap.

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeZkhuZC01MUFHT1k @asalsman

**Comment by asalsman** [comment]
Done:
- Mobile responsiveness is inherited from existing upcoming event display. Small code change/addition because Public Notices have a different date field.
- Featured Public Notice now has a "Notice Details" button instead of an "Event Details" one.
- Public Notices are rendering with Events in proper chronological order.
- "See All" button functionality remains unchanged per spec.
- Hover states for Public Notices are inherited from existing layout and function in the exact same manner as Events
- Public Notices now have the proper default icon (thank you @sebastianebarb, @hackajesse)

In Progress:
- A public notice can now be featured. There are style fixes/updates for Featured Item that need to be made due to inheritance. 

Up next:
- Pulling Featured Item out of returned results for rest of upcoming events
- Get Public Notice Dept. displaying on public notices listed in upcoming events
- Clean up styles to be consistent between Events/Public Notices in Upcoming Events.

**Comment by hackajesse** [comment]
Not sure this ticket is done @asalsman. Let's talk tomorrow. Lots of progress, but not quite ready for prime time, me thinks. Moving to In Progress.
cc @matthewcrist

**Comment by asalsman** [comment]
@hackajesse: At the moment, this is a "feature," not a bug. There are display repercussions related to moving the Neighborhoods field to being a subset of the places field. These repercussions involve both the rendering of a public notice, and potential calendar/public notice front display problems. 

@jimafisk and I discussed for a bit and then raised with @matthewcrist. Consensus was to leave Public Notices as is (for the moment) and then assess and deal with the issues that came up.

This is in part because Neighborhood (not Places) is a requirement of actually creating a Public Notice.

I should be in between 7:30 and 7:45 tomorrow and we can parlez in person.

**Comment by asalsman** [comment]
@hackajesse Everything for this, as far as I can tell, is done. If there's anything else I need to do, holler.
