### ISSUE TITLE
Make featured events disappear after they happen (on events component)

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#360]
As a website viewer, I shouldn't see a featured event on an events component duplicated among the non-featured events. 

As a website viewer, I shouldn't see a featured event in the events component if the day of that event has passed.

- [x] A content author can make an event featured on an Events component
- [x] A content author can remove an event from being featured on an Events component
- [x] A website viewer can see an event as "featured" (large format card) on an Events component
- [x] A website viewer only sees an event shown once in an Events component, even if that event is featured.
- [x] A featured event automatically disappears 6 hours after it starts

**Comment by hackajesse** [comment]
Need to add when the card disappears.

**Comment by asalsman** [comment]
BTW: Once issue #334, the deduping functionality will be available.

**Comment by asalsman** [comment]
Just finished testing. Everything works as expected, based on reqs in this issue.

**Comment by reillyzlab** [comment]
On Hub, even if event is featured it still shows up in the four items below (i.e. doesn't disappear and move an event up into component as it gets featured). So, you see event twice in same component.

Will confirm tomorrow whether the disappear portion works.

**Comment by jimafisk** [comment]
Changes on #627 might have merge conflict with #609 since both target upcoming_events view. I've gotten this working locally by editing the upcoming_events (view) > Upcoming Events (display) per the following steps:
1. Add a new relationship to get Paragraph info from the original node
![1_relationship_to_paragraph](https://cloud.githubusercontent.com/assets/5913244/25666790/8868e6de-2fef-11e7-85b6-b8b7e295ba0d.png)
2. Add a second relationship using the first to get info from the node that is referenced by the paragraph item
![2_relationship_from_paragraph_to_referenced_entity](https://cloud.githubusercontent.com/assets/5913244/25666958/073cb3fa-2ff0-11e7-904b-e70c31826bec.png)
3. Add a NID field using the 2nd relationship to the node referenced by the paragraph
![3_add_nid_with_relationship](https://cloud.githubusercontent.com/assets/5913244/25667082/6f80f3ea-2ff0-11e7-9a01-241d47ac2b83.png)
4. Add a filter that only displays content that doesn't have a value for the Node's paragraphs' referenced node's NID (aka hasn't been referenced in the Featured Item field).
![filter](https://cloud.githubusercontent.com/assets/5913244/25667187/c90cb340-2ff0-11e7-9eff-82ace4189076.png)

Here's a screenshot of the display before this is working:
![before](https://cloud.githubusercontent.com/assets/5913244/25667263/fecb4ef6-2ff0-11e7-838d-a84ae67b5303.png)

Here's after:
![after](https://cloud.githubusercontent.com/assets/5913244/25667273/07283f0a-2ff1-11e7-83f4-65c17c13f75f.png)

**Comment by matthewcrist** [comment]
I merged in #609. Can you pull develop and handle any conflicts?

**Comment by jimafisk** [comment]
Merge conflicts were resolved for PR #627 and branch has been merged with develop.

**Comment by reillyzlab** [comment]
Can't test b/c of https://github.com/CityOfBoston/boston.gov/issues/694
