### ISSUE TITLE
Unable to add tabbed content type into related content

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#492]
A content contributor is unable to add tabbed content into any related content field.

Should be able to add to 'other related content' field.

**Comment by matthewcrist** [comment]
Putting this as an enhancement as we didn't have tabbed content in Boston.gov at the time of related content changes.

**Comment by jimafisk** [comment]
There appears to be three content types using field_related_content (Other related content): 
- Event
- Post
- Public Notice

I'll add "Tabbed Content" to the Entity Selection > Target Bundles for these three content types. Do we need to be able to reference Tabbed Content elsewhere?

**Comment by matthewcrist** [comment]
That should do it…I think...

On Tue, Apr 25, 2017 at 12:42 PM Jim Fisk

<
mailto:Jim Fisk <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

There appears to be three content types using field_related_content (Other related content):

Event

Post

Public Notice

I'll add "Tabbed Content" to the Entity Selection > Target Bundles for these three content types. Do we need to be able to reference Tabbed Content elsewhere?

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/CityOfBoston/boston.gov/issues/492#issuecomment-297090672
, or
