### ISSUE TITLE
Live streamed events have extra alert on Boston.gov event list

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#50]
In the CMS, add a checkbox in the Video component that indicates an event will be live streamed. "This event will be streamed live."

On /events:
- Add play-with-circle icon (keep it same color as event title) immediately before the event title vertically aligned with the text. _This should happen for all events with a video component._ Exclude the word "Live".
- For live streamed events, keep the word "Live" to the right of the icon.
- In the event dropdown, change Event Details button copy (number 6 in the comp) to "Watch it live". This only happens for events that are being live streamed, not for plain video component events.

On an event thumbnail:
Use "What it live" as copy and play-with-circle icon from number 9 per the comp below the event title, left and bottom justified.

There will be a video component in the actual event page, so no need to change anything there.

Remaining questions for @asalsman :
- Can a pre-defined image show in the video component until the event begins when someone clicks play? Otherwise, it'll be the regularly required image per the video component now and simply play whatever the live stream is showing at that moment.

[calendar-lite-page.pdf](https://github.com/CityOfBoston/boston.gov/files/530278/calendar-lite-page.pdf)

**Comment by hackajesse** [comment]
@matthewcrist what questions do you have?

**Comment by asalsman** [comment]
- Is there an example of an event page with a video on it right now? I want to make sure when I'm recreating a video in dev, I'm doing it right.
- Placement of "Watch it Live" flag on mobile/tablet?
- Any indications on the individual event pages or just the calendar front?
- Will we know the URL of the video before hand?
- Do we only show the flag of "watch it live" when it's actually live? If not, should there be another indicator that a user COULD (in the future) watch it live?
- "Can a pre-defined image show in the video component until the event begins when someone clicks play?" On one hand, I'd say "most likely," on the other I'd ask what happens if the stream doesn't start right away? I imagine this as some sort of scheduling magic that says "At 9am, we go from showing static image to video player" but that could also prove problematic if/when the stream doesn't start when expected.

**Comment by hackajesse** [comment]
Progressive enhancement upgrade:

If a user doesn't have JS enabled, the YouTube video doesn't work anyways, so...

- Keep the "Event details" button as-is on /events detail dropdown
- In the page w/the video component, rework the video component to say "Thanks for your interest! You will need to enable JavaScript on your browser if you want to watch the video."

If a user has JS enabled:

- use the start time field for 

to be continued....

**Comment by hackajesse** [comment]
Note that this applies both to event content types AND public notice content types as those continue to be created.

**Comment by matthewcrist** [comment]
This is ready on production.

**Comment by hackajesse** [comment]
This looks good. Started new issues w/bugs or adjustments ( #212 #213 #214 #215 ). Closing.
