### ISSUE TITLE
Issue with upcoming events list

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#526]
Issue with _upcoming_ events list. List isn't populating upcoming events on some content types. No disruption to lists already created/being used, but issues with list not displaying events when current list is edited or new list is added. Happens to new and pre-existing pages. Content contributor can select upcoming events list in back end of CMS, but when they save the 'draft' doesn't display any upcoming events.

Four options available to choose in list dropdown:
upcoming_events - Upcoming Events (top item in list) > This is the list that works/brings in upcoming events [this is functionally how this should work]
upcoming_events - Events (second to bottom item in list) > Seems to be non-functioning
upcoming_events - Upcoming Events (bottom item in list) > Seems to be non-functioning
upcoming_events - Master (top item in list on tabbed page) > Seems to work

Working fine on the following page types:
Article
Landing
Listing
How To
Public Notice 
Tabbed

Not working on the following pages types:
Department profile
Event
Guide
Person
Place
Post
Program/Initiative
Script

**Comment by matthewcrist** [comment]
@reillyzlab this should be the way it works. we can remove the others from the list.

**Comment by jimafisk** [comment]
For my reference, upcoming_events is a list within the "List" component type:

![upcoming_events](https://cloud.githubusercontent.com/assets/5913244/25441958/b4cbf42e-2a71-11e7-8a17-e95c73887263.png)

We need to
1) Remove non-functioning, duplicate upcoming_events options from the dropdown
2) Fix the main upcoming_events option that isn't working on the content types specified above

**Comment by jimafisk** [comment]
The first issue (duplicated upcoming_events options) 

![misc_upcoming_events_options](https://cloud.githubusercontent.com/assets/5913244/25444351/c5303030-2a78-11e7-8523-82e84197c469.png)

is because the View "Upcoming Events" has several displays used for this throughout the site

![view_displays](https://cloud.githubusercontent.com/assets/5913244/25444367/d1443d12-2a78-11e7-81ea-584698440bdf.png)

but the allowed value list for the component is set at the View level and not the display level

![allowed_values](https://cloud.githubusercontent.com/assets/5913244/25444382/e48c2bf0-2a78-11e7-9da3-ae654430f22c.png)

**Proposed solution:** Create a new view (or clone the original) and make the only display available be the default that is needed for this component. Reference that new view in the List component. @reillyzlab @matthewcrist would that work?

**Comment by reillyzlab** [comment]
I defer to @matthewcrist on this

**Comment by matthewcrist** [comment]
This is ready on staging

**Comment by reillyzlab** [comment]
Leaving ticket because issue with entire ticket rather than one off issues.

This is not working on any content type. More specifically:

Was working on these content types when originally entered this ticket, but no longer working on:
Article
Landing
Listing
How To
Public Notice
Tabbed

Wasn't working before originally entered this ticket and still not working:
Department profile
Event
Guide
Person
Place
Post
Program/Initiative
Script

**Comment by matthewcrist** [comment]
@reillyzlab I've been able to add upcoming events to all content types in Hub and Boston.gov. Can you include your testing steps?

**Comment by jduffy2001** [comment]
Seeing similar issues to Reilly. I logged into edit-stg.boston.gov. Created and article page

Article page: https://edit-stg.boston.gov/node/25421/edit
Department profile: https://edit-stg.boston.gov/departments/duffy-department-profile

**Comment by jduffy2001** [comment]
Seeing similar issues to Reilly. I logged into edit-stg.boston.gov. Created and article page

Article page: https://edit-stg.boston.gov/node/25421/edit
Department profile: https://edit-stg.boston.gov/departments/duffy-department-profile
Event: https://edit-stg.boston.gov/calendar/duffy-event

**Comment by matthewcrist** [comment]
@jimafisk looks like the component won't display events unless you're an admin now. Can you take a look? This is a blocker.

**Comment by jimafisk** [comment]
Removed node_access check on relationships in view. Let me know if it still gives you trouble. Thanks!

**Comment by jduffy2001** [comment]
Just jumped into person profiles and program profiles and it still doesn't appear to be working.

I can run through the rest of the content types as well.

**Comment by matthewcrist** [comment]
@jduffy2001 I just deployed the fixes to Boston.gov staging. You should be able to see them now.

**Comment by jduffy2001** [comment]
Tested upcoming and related lists, all of these content types looked good:

- Article: https://edit-stg.boston.gov/departments/digital-team/duffy-article
- Department page: https://edit-stg.boston.gov/departments/duffy-department
- Event: https://edit-stg.boston.gov/calendar/duffy-event
- Guide: https://edit-stg.boston.gov/duffy-guide
- How-to: https://edit-stg.boston.gov/duffy-how
- Landing page: https://edit-stg.boston.gov/duffy-landing-page
- Person profile: https://edit-stg.boston.gov/departments/digital-team/duffy-person-profile
- Place profile: https://edit-stg.boston.gov/cemetaries/duffy-place-profile
- Post: https://edit-stg.boston.gov/news/duffy-post
- Program page: https://edit-stg.boston.gov/arts-and-culture/duffy-program-page
- Public notice: https://edit-stg.boston.gov/public-notices/25531

There doesn't appear to be a "related list" for listing pages, but don't think we need one since these pages exist to only pull in lists.

One bug I noticed, when you only have a single event in an "upcoming events" component, the styling looks weird. Here's what it looks like with one event:

![image](https://cloud.githubusercontent.com/assets/7929556/26005311/afc47e5a-3706-11e7-885a-caae7e0aa6a3.png)

And here's what it looks like with two:

![image](https://cloud.githubusercontent.com/assets/7929556/26005348/c1d571bc-3706-11e7-98f8-5cfac82ba1e9.png)

@matthewcrist do you want me to file a separate ticket?

**Comment by reillyzlab** [comment]
Closing b/c moved styling bug into: https://github.com/CityOfBoston/boston.gov/issues/668 (not blocker)

**Comment by reillyzlab** [comment]
Not working on Hub

**Comment by reillyzlab** [comment]
Now working on Hub, but major bug that should hold this push to production until fixed: https://github.com/CityOfBoston/boston.gov/issues/694

**Comment by reillyzlab** [comment]
Resolved, closing
