### ISSUE TITLE
Related Content: Neighborhoods Missing Beacon Hill as Option

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#589]
Related Content - Admin on Events and Posts - Neighborhoods

Beacon Hill is not listed as a neighborhood radio button and should be

Public Notices is fine.

There is a work around via 'related places', but content contributors aren't adding the related neighborhood since all other neighborhoods are listed specifically under 'related neighborhoods'

![image 11](https://cloud.githubusercontent.com/assets/20731897/25247056/b17119a6-25d7-11e7-8d1e-abb07c295320.png)

**Comment by jimafisk** [comment]
@reillyzlab I think the issue here is poor documentation on my part. You should be able to indicate if a place_profile is a neighborhood on the place_profile node itself. I'm attaching screenshots here on how to do that in case someone stumbles across this issue in the future. Please let me know if I should post elsewhere. Thanks!

The steps to fix are as follows:
1) Search for the Neighborhood in question in the content interface (/admin/content) under the content type "Place Profile." Then click edit.

![find_beacon_hill](https://cloud.githubusercontent.com/assets/5913244/25350383/f85dfa0a-28f2-11e7-99dc-558f95c66597.png)

2) On the default "Basic Information" tab on the left, scroll to the bottom of the page and check off the "Neighborhood" box under the "Is a neighborhood" grouping.

![check_neighborhood](https://cloud.githubusercontent.com/assets/5913244/25350747/222ec458-28f4-11e7-8d88-bb0115d305ed.png)

3) Click on the "Publishing options" tab on the left and select "Published" as the "Moderation state." Then click the "Save" button at the bottom of the screen.

![publish_place_profile](https://cloud.githubusercontent.com/assets/5913244/25350518/6e3caec4-28f3-11e7-9adc-22458159a3ce.png)

4) Now if you edit or add an Event (/node/add/event) you should see the neighborhood appear under "Neighborhoods" within the "Related Content" grouping on the "Related Content" tab.

![neighborhood_list](https://cloud.githubusercontent.com/assets/5913244/25350583/a0b275aa-28f3-11e7-92da-aa1625cf6e47.png)

**Comment by matthewcrist** [comment]
@reillyzlab this is just a content issue.

**Comment by reillyzlab** [comment]
@jduffy2001 see above - closing ticket for dev. but @jduffy2001 flag if we need to re-open
