### ISSUE TITLE
Short title bug: Short titles not showing up on saved page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#635]
Bug to ticket in Acceptance QA: #439

When page is saved and a component has a short title entered in the admin, the short title is not appearing on the saved page for the following components:

- [ ] FYI Component

- [ ] hero image

- [ ] video component

- [ ] featured guides

- [ ] user action

See here: https://edit-stg.boston.gov/my-test-article-page

**Comment by jimafisk** [comment]
We'll need to use `field_component_title` on these paragraph bundles or restructure how we're doing short titles. Take for example a working component (List) and a broken component (FYI):

List has `field_component_title`:

![list](https://cloud.githubusercontent.com/assets/5913244/26014376/43511818-372a-11e7-8874-daf3b643eeb2.png)

But FYI uses `field_title`:

![fyi](https://cloud.githubusercontent.com/assets/5913244/26014431/8025e7fa-372a-11e7-8fdb-14e9981448dd.png)

Because of this, in working components (like List) the title gets converted to a link in `sites/all/themes/custom/boston/template.php`:

![preprocess](https://cloud.githubusercontent.com/assets/5913244/26014877/7fb4ca64-372c-11e7-8fdc-96dcffc887ad.png)

and markup is added (importantly the class `subnav-anchor`) to working components via the template at `sites/all/themes/custom/boston/templates/field/field--component--field-component-title.tpl.php`:

![markup1](https://cloud.githubusercontent.com/assets/5913244/26015131/96cd97f2-372d-11e7-8837-66e95d4bb136.png)

...but broken components (like FYI) do not have this template available to them. Without that markup being applied, the javacript in `sites/all/themes/custom/boston/src/js/topic-nav.js` cannot create nav items so the `scroll-link-js` link is never created:

![js1](https://cloud.githubusercontent.com/assets/5913244/26015244/34918fd4-372e-11e7-9130-12b8088b5aa6.png)

@matthewcrist do we want to add `field_component_title` to broken components? We'd have to account for styling differences. Probably easier to preprocess and template `field_title` to add `subnav-anchor`?

**Comment by jimafisk** [comment]
@reillyzlab I spoke with @matthewcrist to create a plan for fixing this. It appears that short titles should definitely be enabled for the video component, but could be skipped for the other paragraph types (FYI Component, hero image, featured guides, user action), do you agree?

If that's the case, I think we might want to explore:

1. Adding `field_component_title` to the Video Component.
2. Migrating the existing data from `field_title` to `field_component_title`
3. Removing `field_title` from the Video Component

**Comment by jimafisk** [comment]
The migration is 2 step process.

Step 1 (https://github.com/CityOfBoston/boston.gov/pull/898):
- Enables a custom module that creates a VBO action that copies values from `field_title` and saves them to `field_component_title`
- Enables a feature that creates a view the shows only nodes that have a video component. This feature references the VBO action created in the custom module
- Profile updates that enable the custom module and the feature on the site
- **Note:** We must then manually run the migration located at `/video-component-title-migration` (protected view only accessible to administrators)

Step 2 (https://github.com/CityOfBoston/boston.gov/pull/899)
- Updates `paragraphs-item--video.tpl.php` to use `field_component_title` instead of `field_title`. This template needs to output `field_component_title` somewhere in order for short titles to work (even if simply printed with the "hidden" class applied)
- Adds `field--field-component-title--video--mode--full.tpl.php` to override `field--component--field-component-title.tpl.php` simply to remove h2 markup and `sh-title` class which was impacting the display of the video title.
- Updates the install profile to remove the temporary custom migration module and feature for the migration view. Also removes a feature and module for a previous (related content) migration.

**Comment by jimafisk** [comment]
The migration on stg should be all set at this point and short titles for videos should be working. @reillyzlab can you test when you get a chance? Thanks!

**Comment by reillyzlab** [comment]
working on staging
