### ISSUE TITLE
Short title needed: Forgot cabinet component in specs

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#636]
Forgot to include this component in specs for short title additions/edits

Cabinet component needs a short title added into the workbench admin and to appear on the website.

Short title should not be required.

Short title should include the following help text:
The short title is used to populate the in-page navigation. Please keep it short: one to three words is ideal. Example can be found on boston.gov/winter/.

**Comment by reillyzlab** [comment]
Short title is added into this component, is not required, and has help text, so those pass. 

But, short title is not appearing.

**Comment by jimafisk** [comment]
The short title not appearing on the node view is because the Cabinet paragraph bundle uses `field_title` instead of `field_component_title`

![cabinet_field_title](https://cloud.githubusercontent.com/assets/5913244/26533786/bf0bbc38-43eb-11e7-87a7-77df966a0352.png)


The reason why this prevents short titles from working is detailed on issue #635

**Comment by matthewcrist** [comment]
Closing since this is covered by #635.
