### ISSUE TITLE
Components should know what content types they belong to

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#677]
In order to prevent issues with exporting features, we need to update the components so that they know which content types they belong to.

**Comment by jimafisk** [comment]
1) The only reference fields we're interested in are `field_components` and `field_sidebar_components`
2) The enabled paragraph bundles referenced in these fields might not always be the same across all content types
3) The highest priority is to be able to set these values in one place. This helps avoid merge conflicts if another dev is updating the same bos_content_type feature.

In order to avoid having to edit and save each content type separately to update field_config_instance data for the paragraph reference fields, we can use Paragraphs Reference Manager: https://www.drupal.org/project/paragraphs_reference_manager. Ideally this module would only be downloaded and enabled for local builds.

In order to avoid merge conflicts and allow all `field_components` and `field_sidebar_components` to be updated without having to export separate features for each content type, we should remove these fields from "Field Instances" of all bos_content_type features (e.g. for `bos_content_type_article` remove `node-article-field_components` and `node-article-field_sidebar_components`) and add them to a single new feature that only tracks these field instances, but does so across all content types.

I'm testing this approach locally to confirm that no migration will be required.

**Comment by jimafisk** [comment]
The steps to enable bundles through the paragraphs interface are detailed in PR #698

**Comment by matthewcrist** [comment]
I've verified this is working. @reillyzlab and @jduffy2001 if you could just run through staging for Boston.gov and Hub to just make sure there's no new issues with adding components to content types. Should just be able to test a couple different pages.

**Comment by reillyzlab** [comment]
Checked and believe fine. @jduffy2001 can you check and close if okay for you

**Comment by jduffy2001** [comment]
Looks good.
