### ISSUE TITLE
Update "neighborhoods" section in "related items" of public notices

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#740]
The "neighborhoods" section in "related items" of the public notice content type doesn't function in the why it should. Instead of tagging neighborhoods so that a notice appears on that [neighborhood page](https://www.boston.gov/neighborhoods) when it's published, this section is just adding to the neighborhoods section of a post:

![image](https://user-images.githubusercontent.com/7929556/27446238-d6bf68e4-574a-11e7-9e65-56326219c02c.png)
![image](https://user-images.githubusercontent.com/7929556/27446222-c9e1f43e-574a-11e7-9a86-14744e92e393.png)

@jimafisk and I talked this out last week, and this appears to be the case.

An ideal version of this "neighborhoods" field would:

- add to that "neighborhoods" section of a posting (second image above), and
- tag a notice so that it appears on a neighborhood page in the "upcoming events" component when published.

**Comment by jimafisk** [comment]
This comment describes difference at the Drupal field level: https://github.com/CityOfBoston/boston.gov/issues/685#issuecomment-305276626

@jduffy2001 did we determined that having two separate fields is not acceptable (this is how Events currently work)? Based on our conversation it sounded like this would result in duplicating manual entry since the values would always be the same in both fields. Consolidating the fields would likely require a migration at the very least, but also has considerations for replicating the select all / display logic for Citywide or related filters depending on which field we stick with. We should loop in with @matthewcrist as this could effect multiple site areas.

**Comment by jduffy2001** [comment]
@jimafisk I would like to avoid duplication as much as possible, but if it's a heavy lift, we could just set up public notices as we do events now. Ideally, the "neighborhoods" section of related content would be what causes this section of the public notice to appear:

![image](https://user-images.githubusercontent.com/7929556/28996971-82051e2e-79d8-11e7-93b5-ae056f05e0bf.png)

However, a bigger question might be, is this "neighborhoods" section as shown above even useful. I get it on the [events page of boston.gov](https://www.boston.gov/events), because we're giving people an ability to filter by neighborhood. But, that option doesn't exist right now on public notices. This doesn't matter, though, if we decide to add that filter to our [main public notices page](https://www.boston.gov/public-notices).

**Comment by reillyzlab** [comment]
Too big of level of effort for now
