### ISSUE TITLE
Enhancements to link to content button in WYSIWYG

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#810]
When a content author uploads a pdf in the WYSIWYG field, they use the "link to content" option located here:

![image](https://user-images.githubusercontent.com/7929556/28997057-47d4a2fe-79da-11e7-8ad4-866ff28a3d1f.png)

One content author noted that the folders that appear here are starting to add up: 

![image](https://user-images.githubusercontent.com/7929556/28997068-6e65b57a-79da-11e7-8299-567e652d8a7b.png)

I would like to make two enhancements to the link to content option.

1. Can we switch the order of the folders so that the order is current month at the top, followed by older months?
2. Right now, a content author has to click on the current month's folder to see the upload button at the top left hand side of the screen. Could we set it up so that the current month is always picked by default? My concern is that some content authors might miss the step of clicking on the current month, and then never see the upload button.

I can break these requests into separate tickets if need be.

**Comment by jimafisk** [comment]
I've always run into user experience issues being reported when using IMCE (https://www.drupal.org/project/imce) to upload images/files. It might be worth looking into an entirely different approach to this. It looks like currently we're using the LinkIt module (https://www.drupal.org/project/linkit) to allow users to discover actual system paths, which integrates with IMCE to handle the file upload part, which may be why we used it in the first place. There are a couple of other ways to handle the file upload aspects, including CKEditor Media Browser (https://www.drupal.org/project/ckeditor_media) and One Click Upload (https://www.drupal.org/project/ocupload).

I think CKEditor Media Browser would be a great approach because it still allows us to categorize and browse an archive of uploaded files, while simplifying the process of uploading new files. Here's a gif of what this experience looks like:

![file_upload](https://user-images.githubusercontent.com/5913244/29789306-97122ffe-8c03-11e7-9384-d7667119373b.gif)

@jduffy2001 what are your thoughts on this? @matthewcrist wanted to loop you in on this as well, since it would add a contrib module.

**Comment by matthewcrist** [comment]
@jimafisk this looks like it would be fine. Assuming we would get rid of ICME?

**Comment by jimafisk** [comment]
Yeah I don't see any reason to keep it around if we implement CKEditor Media Browser. The small difference is we would use the regular link button instead of the LinkIt button to upload files:

![linkit_vs_link](https://user-images.githubusercontent.com/5913244/29875272-79afca9c-8d67-11e7-87ec-b3823b1c5668.png)

**Comment by matthewcrist** [comment]
Can you get this setup in a PR? Then we can deploy that to a dev instance for James to play with?

a, pre, code, a:link, body { word-wrap: break-word !important; }

**Comment by jimafisk** [comment]
PR #849 should be ready for testing. As noted on the PR, we'll need to have the feature revert applied before disabling IMCE and removing it. IMCE file uploads are already disabled in the LinkIt settings, so the functionality will not change from this PR, only the codebase will be cleaner. Thanks!

**Comment by matthewcrist** [comment]
After testing this out, we're going to keep IMCE as is.

**Comment by matthewcrist** [comment]
Reasons are that:

- Loses functionality of LinkIt for finding content to link to
- Loses ability to automatically switch between edit.boston.gov and boston.gov domains
- Clunkier experience

**Comment by jimafisk** [comment]
@matthewcrist makes sense. Should we revisit the original purpose of this issue (e.g. improving IMCE folder structure), or are we ok leaving as is?

**Comment by matthewcrist** [comment]
Let’s leave as is for now. I’ll mark this as a Drupal 8 wishlist item.

On Thu, Aug 31, 2017 at 1:26 PM Jim Fisk

<
mailto:Jim Fisk <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/matthewcrist
makes sense. Should we revisit the original purpose of this issue (e.g. improving IMCE folder structure), or are we ok leaving as is?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/CityOfBoston/boston.gov/issues/810#issuecomment-326365808
, or
