### ISSUE TITLE
"Featured" news and events showing up at bottom of components

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#822]
This is a bug that we've had before. The "featured" news and events items are now also appearing in the bottom of the news and announcements and upcoming events components. The way it worked before, if you placed a featured item manually at the top of the component, it then wouldn't appear in that bottom part that gets pulled in automatically. 

You can see the bug here [on the homepage](https://www.boston.gov/):
![image](https://user-images.githubusercontent.com/7929556/29328113-6e352b8e-81bf-11e7-933d-2c8c7c0793e9.png)

And here for the events component:
![image](https://user-images.githubusercontent.com/7929556/29328133-7f9e224a-81bf-11e7-9bb0-52b9b81b02ac.png)

**Comment by jimafisk** [comment]
It looks like we fixed this previously only for the "Upcoming Events" view (/admin/structure/views/view/upcoming_events/edit), so I think this is an oversight rather than a regression. I'm applying the same logic to the "News & Announcements" view (/admin/structure/views/view/news_announcements/edit) now. 

@jduffy2001 should this be applied to the specific displays (e.g. Departments, News, People, etc.), or is it only needed on the general "Most Recent" display? Thanks!

**Comment by jimafisk** [comment]
Oh I'm just seeing the second part about this breaking on events too... I'll look into that.

**Comment by jimafisk** [comment]
When I tested with the "Upcoming Events" display, it appears to be working:

![events_removed_from_list](https://user-images.githubusercontent.com/5913244/29724074-1e794584-8995-11e7-8523-afc5e9c72ee5.png)

This functionality does not appear to be setup for any of the "Related Events" (/admin/structure/views/view/related_events/edit) displays. 

I assume this needs to be setup for both events, related events, news, and related news?

**Comment by matthewcrist** [comment]
This is done.
