### ISSUE TITLE
Search menus should be same as Boston.gov main menu

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#923]
The main menu on Boston.gov and the main menu at search.boston.gov are showing up in a different order. We also removed the "programs and initiatives" page from the boston.gov main menu, but it's still showing up at search.boston.gov, and it's now a broken link:

Boston.gov layout:
![image](https://user-images.githubusercontent.com/7929556/32729446-ce38c8e6-c851-11e7-9d7f-d97831992b5d.png)

Search.boston.gov layout:
![image](https://user-images.githubusercontent.com/7929556/32729467-e5445fc8-c851-11e7-91a5-21e670d66a1c.png)

Can we set it up so that search mirrors Boston.gov? The same thing goes for our footer:

Boston.gov footer:
![image](https://user-images.githubusercontent.com/7929556/32729503-0e9216a4-c852-11e7-97f8-f5042fe1b958.png)

Search.boston.gov footer:
![image](https://user-images.githubusercontent.com/7929556/32729527-1ba5cfc0-c852-11e7-9559-7758b31efdf8.png)

The header menu for search is also missing the "translate" option, but I'm not sure if that's intentional on that page. I know our translation tool can be hit or miss.

**Comment by reillyzlab** [comment]
@jduffy2001 @jimafisk and/or @matthewcrist let's use this time to transfer the app to the swiftype module on boston.gov

**Comment by reillyzlab** [comment]
@matthewcrist or @jimafisk can you write testing steps for the boston.gov search module so that @BrutiAnteneh can QA once on staging?

**Comment by matthewcrist** [comment]
Testing steps for @BrutiAnteneh:

- Go to site, click on search and perform a search
- Validate that user is on www.boston.gov/search and not search.boston.gov
- Perform same search on search.boston.gov
- Verify that search results are the same
- Click on search result in www.boston.gov/search results
- Verify that user sees correct page
- Verify in Swiftype that click has been tracked
- Perform filter actions
- Verify that filters are applied correctly
- Verify that paginated through results maintains filters

**Comment by BrutiAnteneh** [comment]
The issue did not pass - could not access www.boston.gov/search on [staging site](https://edit-stg.boston.gov/search):
![923](https://user-images.githubusercontent.com/33470951/34422176-d0aa349e-ebe1-11e7-94a7-ec272f83abbe.png)

**Comment by jimafisk** [comment]
@cob-hondo is this fixed by https://github.com/CityOfBoston/boston.gov/pull/958 ?

**Comment by matthewcrist** [comment]
Yes. It should fix the lib loading issue.

**Comment by jimafisk** [comment]
@BrutiAnteneh can you test this again on staging? Thanks!!

**Comment by BrutiAnteneh** [comment]
When I tested a search query on on staging, the following popped up: 

![image](https://user-images.githubusercontent.com/33470951/34441172-fa9a27f4-ec87-11e7-84c5-7e08eade117b.png)

**Comment by jimafisk** [comment]
@BrutiAnteneh I forget to reset a few environment variables when copying the database from prod. I made these changes and it appears to be working now, can you try again to confirm? Thank you!

**Comment by BrutiAnteneh** [comment]
This issue did not pass as expected due to pagination errors occurring on both **www.boston.gov/search**  and **search.boston.gov** (see table below).

 

Although search filters are working correctly, I noticed that for _many_ of the filter types, pagination does not end on the page with the last search result but continues with no apparent limit.


On **www.boston.gov/search**, pagination continues beyond the final search result, offering up blank pages:
![923 documents search pagination -edit-stg boston gov-2018-01-02-23-06-28-653](https://user-images.githubusercontent.com/33470951/34509262-09b2d9f2-f016-11e7-8738-f68b1e012a56.png)




Similarly, on **search.boston.gov**, pagination continues with a message appearing on each page: 

![923 documents search dot boston-search boston gov-2018-01-02-22-49-35-047](https://user-images.githubusercontent.com/33470951/34509295-4ab009ac-f016-11e7-95ed-185a190272b3.png)

Worth noting: a search query performed on both sites produces identical results, but pagination errors do not occur on identical filter types ( e.g. Events, Programs, How-to).

| Filter Type  | Pagination Functioning  boston.gov/search| Pagination Functioning search.boston.gov  | 
| ------------- | ------------- | -------------|
| Documents | [no](https://edit-stg.boston.gov/search?page=71&query=towing&facet%5B0%5D=documents) | [no](http://search.boston.gov/?facet%5B%5D=documents&page=71&query=towing) |
| News |  [no](https://edit-stg.boston.gov/search?page=60&query=towing&facet%5B0%5D=post) | [no](http://search.boston.gov/?facet%5B%5D=post&page=60&query=towing) |
| Public Notices | [no](https://edit-stg.boston.gov/search?page=8&query=towing&facet%5B0%5D=public_notice) | [no](http://search.boston.gov/?facet%5B%5D=public_notice&page=8&query=towing) | 
| Articles | [no](https://edit-stg.boston.gov/search?page=7&query=towing&facet%5B0%5D=article) | [no](http://search.boston.gov/?facet%5B%5D=article&page=7&query=towing) |
| Events  | yes | [no](http://search.boston.gov/?facet%5B%5D=event&page=4&query=towing) |
| Programs   | yes | [no](http://search.boston.gov/?utf8=%E2%9C%93&query=towing&facet%5B%5D=program_initiative_profile) | 
| How-To | yes | [no](http://search.boston.gov/?facet%5B%5D=how_to&page=3&query=towing) | 
| Departments | yes | yes |
| People | yes | yes | 
| Guides | yes | yes |

**Comment by cob-hondo** [comment]
@brutianteneh we’re there any other issues for this, or is this the only one?

**Comment by BrutiAnteneh** [comment]
@cob-hondo this was the only one - everything else worked.

**Comment by cob-hondo** [comment]
Awesome!

**Comment by jimafisk** [comment]
@BrutiAnteneh the pagination issue should be fixed on staging. Can you test again to make sure we're passing now? Thanks!

**Comment by BrutiAnteneh** [comment]
@jimafisk this is now passing.
