### ISSUE TITLE
mobile: transaction icons broken on homepage, department and guide pages

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/boston.gov#974]
## The Problem:  
Transaction icons are breaking on mobile. Reference: @jduffy2001 noticed this in #734 
### Working on Desktop:
Windows 7: Chrome (latest) Firefox (latest)
Apple os x: Chrome 10, Safari 10.5
### Mobile Devices tested:
**iPhone: (iOS 11)**
 iPhone 6: 375x667
 iPhone: 6 Plus, 7, 7 Plus - 414x736

**Android: (6.0.1)**
Google Pixel; 360x640
Samsung Galaxy S5, S7 - 360x640

## Homepage (mobile):
URL: https://www.boston.gov/
**Screenshot Device Details:**
OS: Android 8.1.0
Device: Google Pixel
Screen Resolution: 360x640 px
**Portrait:**
![image](https://user-images.githubusercontent.com/33470951/35014269-fb25b382-fadd-11e7-8146-b0473d4094ed.png)

 **Landscape (640x360 px):**
![image](https://user-images.githubusercontent.com/33470951/35067790-16ebb95c-fba3-11e7-84c6-5a509ff49600.png)

Note: Tested different breakpoints using Chrome and Firefox browser developer tools. Chrome accurately display the mobile bug, but Firefox does not:
![image](https://user-images.githubusercontent.com/33470951/35059624-d86bc56e-fb89-11e7-9359-2c29b6c9c81c.png)

### Department Pages with Broken Transaction Icons: 
I've found broken Transaction icons on several department pages, including:
**Assessing Department Page**
URL: https://www.boston.gov/departments/assessing
**Note:** Within this transaction grid, we see the same icon appearing as both broken and functioning at 767 pixels. 
**Breaks at 767 px and below:**
![image](https://user-images.githubusercontent.com/33470951/35061606-bf3040e2-fb8f-11e7-9865-878a7678f638.png)
**Functioning at 768 px and above:** 
![image](https://user-images.githubusercontent.com/33470951/35061866-7a473746-fb90-11e7-9d4b-bea3081d8ba5.png)
**Archives and Records Management**
same responsive breakpoints as above
URL: https://www.boston.gov/departments/archives-and-records-management
**Broadband and Cable:**
same breakpoints as above
URL: https://www.boston.gov/departments/broadband-and-cable

**Fire Operations:**
URL: https://www.boston.gov/departments/fire-operations
**View on iPhone 6**
![screen shot on jan 18th at 12_05 pm](https://user-images.githubusercontent.com/33470951/35111066-5350edf4-fc48-11e7-9c86-d29c1411c323.png)
**Working at 464 px and above**
![screen shot on jan 18th at 12_39 pm](https://user-images.githubusercontent.com/33470951/35112697-ccd69544-fc4c-11e7-882b-3ca0f3a6ef64.png)

**Breaks at 463 px**
![screen shot on jan 18th at 11_54 am](https://user-images.githubusercontent.com/33470951/35111031-40f00a64-fc48-11e7-9aff-3a56a5210ea3.png)

**Fire Prevention:**
URL: https://www.boston.gov/departments/fire-prevention

## Examples On Guide Pages:

**Having a Car in the City: has 2 transaction grids** 

URL: https://www.boston.gov/having-car-city#get-it-done
![screen shot on jan 18th at 10_10 am](https://user-images.githubusercontent.com/33470951/35105178-f5930bb6-fc38-11e7-85c2-6d42a0456ecb.png)

URL: https://www.boston.gov/having-car-city#parking-permit

![screen shot on jan 18th at 10_12 am](https://user-images.githubusercontent.com/33470951/35105506-d2ef1586-fc39-11e7-9d06-bb54eb447e44.png)

### Low-Income Resources Guide:
URL :https://www.boston.gov/low-income-resources#how-to-%E2%80%A6
![screen shot on jan 18th at 10_54 am](https://user-images.githubusercontent.com/33470951/35107087-0877deaa-fc3e-11e7-90de-f3162265db7c.png)

### Starting a Business Guide:
URL: https://www.boston.gov/starting-business#how-to%E2%80%A6
![screen shot on jan 18th at 10_06 am](https://user-images.githubusercontent.com/33470951/35106950-a2cc255c-fc3d-11e7-8141-16fde4edc32e.png)

### Visiting Boston Guide:
URL:  https://www.boston.gov/visiting-boston#get-started
![screen shot on jan 18th at 10_49 am](https://user-images.githubusercontent.com/33470951/35106931-9732cda4-fc3d-11e7-877a-ef78cb7c3aa0.png)

**Comment by BrutiAnteneh** [comment]
## Examples On Guide Pages:

**Having a Car in the City: has 2 transaction grids** 

URL: https://www.boston.gov/having-car-city#get-it-done
![screen shot on jan 18th at 10_10 am](https://user-images.githubusercontent.com/33470951/35105178-f5930bb6-fc38-11e7-85c2-6d42a0456ecb.png)

URL: https://www.boston.gov/having-car-city#parking-permit**

![screen shot on jan 18th at 10_12 am](https://user-images.githubusercontent.com/33470951/35105506-d2ef1586-fc39-11e7-9d06-bb54eb447e44.png)

### Low-Income Resources Guide:
URL :https://www.boston.gov/low-income-resources#how-to-%E2%80%A6
![screen shot on jan 18th at 10_54 am](https://user-images.githubusercontent.com/33470951/35107087-0877deaa-fc3e-11e7-90de-f3162265db7c.png)

### Starting a Business Guide:
URL: https://www.boston.gov/starting-business#how-to%E2%80%A6
![screen shot on jan 18th at 10_06 am](https://user-images.githubusercontent.com/33470951/35106950-a2cc255c-fc3d-11e7-8141-16fde4edc32e.png)

### Visiting Boston Guide:
URL:  https://www.boston.gov/visiting-boston#get-started
![screen shot on jan 18th at 10_49 am](https://user-images.githubusercontent.com/33470951/35106931-9732cda4-fc3d-11e7-877a-ef78cb7c3aa0.png)

**Comment by reillyzlab** [comment]
@BrutiAnteneh is going to:

1. Replace all pngs with svg files for both sites
2. Resolve any of the issues with the small circle icons

**Comment by BrutiAnteneh** [comment]
Determined that this is an adobe illustrator-related issue. @carolinestj will re-export the .svg icons and send to @jimafisk to reupload.

**Comment by jimafisk** [comment]
These icons need to be uploaded manually since they reside in Drupal's file system and not as part of the template / pattern lib. I'm currently going through and uploading new icons for the pages outlined in this issue:
- https://www.boston.gov/
- https://www.boston.gov/departments/assessing
- https://www.boston.gov/departments/archives-and-records-management
- https://www.boston.gov/departments/broadband-and-cable
- https://www.boston.gov/departments/fire-operations
- https://www.boston.gov/departments/fire-prevention
- https://www.boston.gov/having-car-city#get-it-done
- https://www.boston.gov/having-car-city#parking-permit
- https://www.boston.gov/low-income-resources#how-to-%E2%80%A6
- https://www.boston.gov/starting-business#how-to%E2%80%A6
- https://www.boston.gov/visiting-boston#get-started

For reference, here are the images that are being replaced:
- https://edit.boston.gov/sites/default/files/experiential_icons_real_estate_taxes.svg 
- https://www.boston.gov/sites/default/files/transactions-icon-08-2016/experiential_icons_real_estate_taxes.svg
- https://www.boston.gov/sites/default/files/transactions-icon-12-2016/experiential_icons_3_computer_.png
- https://www.boston.gov/sites/default/files/experiential_icons_city_tv_.svg
- https://www.boston.gov/sites/default/files/transactions-icon-03-2017/become_a_firefighter.svg
- https://www.boston.gov/sites/default/files/experiential_icons_fire_detail.svg
- https://www.boston.gov/sites/default/files/icon-parking-ticket_50.png and https://www.boston.gov/sites/default/files/icon-renew-parking-permit_49.png
- https://www.boston.gov/sites/default/files/icon-license_49.png and https://www.boston.gov/sites/default/files/icon-change-districts_50.png and https://www.boston.gov/sites/default/files/icon-guest-parking-pass_50.png
- https://www.boston.gov/sites/default/files/experiential_icons_tpass_0.svg
- https://www.boston.gov/sites/default/files/icon-silverware_10.png and https://www.boston.gov/sites/default/files/icon-food-truck_10.png and https://www.boston.gov/sites/default/files/icon-help_10.png
- https://www.boston.gov/sites/default/files/transactions-icon-08-2016/berdo_-_building_list.png

**Comment by jimafisk** [comment]
@BrutiAnteneh these should all be uploaded at this point, can you check to make sure I didn't miss anything? Thanks!

**Comment by BrutiAnteneh** [comment]
The issue passed as expected.
Testing confirmed all problematic icons documented in this ticket have been removed from production and replaced with working icons. Excellent work @carolinestj and @jimafisk!
